# Creating Numpy arrays

In [1]:
import numpy as np

## By transforming standard lists into NumPy array:

### For 1D arrays

In [2]:
l1=[1,2,3,4,5,6]
type(l1)

list

In [3]:
l1=np.array(l1)
l1

array([1, 2, 3, 4, 5, 6])

In [4]:
type(l1)

numpy.ndarray

### For 2D arrays

In [5]:
l2=[[1,2,3],[4,5,6]]
l2

[[1, 2, 3], [4, 5, 6]]

In [6]:
type(l2)

list

In [7]:
l2=np.array(l2)
l2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(l2)

numpy.ndarray

## By using Built-in Methods:

### arange() method

In [9]:
l3=np.arange(1,11)
l3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
l4=np.arange(0,21,3)
l4

array([ 0,  3,  6,  9, 12, 15, 18])

### zeros() method

In [11]:
l5=np.zeros(3)
l5

array([0., 0., 0.])

In [12]:
l6=np.zeros((4,4))
l6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones() method

In [13]:
l7=np.ones(4)
l7

array([1., 1., 1., 1.])

In [14]:
l8=np.ones((3,5))
l8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace() method

In [15]:
l9=np.linspace(0,10,3)
l9

array([ 0.,  5., 10.])

In [16]:
l10=np.linspace(1,25,25)
l10

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

### eye() method (creating identity matrix)

In [17]:
l11=np.eye(5)
l11

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## By using Random module:

### random.rand() method

In [18]:
l12=np.random.rand(5)
l12

array([0.981457  , 0.88958099, 0.61383397, 0.3202787 , 0.51818862])

In [19]:
l13=np.random.rand(4,5)
l13

array([[0.67959985, 0.94505665, 0.35214904, 0.26983591, 0.36302195],
       [0.89423873, 0.43819869, 0.51165474, 0.8919981 , 0.90457999],
       [0.93867393, 0.34088689, 0.93191956, 0.42042791, 0.09012225],
       [0.67508849, 0.85078738, 0.54722348, 0.16539445, 0.78850466]])

### random.randn() method

In [20]:
l14=np.random.randn(4)
l14

array([-1.34055042,  1.55440222, -1.34226394,  1.2806442 ])

In [21]:
l15=np.random.randn(3,4)
l15

array([[-0.49131366, -0.50661295, -0.33561279, -0.61246986],
       [-1.70911753, -0.51294974, -1.3561263 ,  0.60716367],
       [-0.21600244, -1.51908702, -1.50644758,  0.86682853]])

### random.randint() method

In [23]:
l16=np.random.randint(0,101,5)
l16

array([65, 45,  0, 28, 69])

In [24]:
l17=np.random.randint(1,101,(5,4))
l17

array([[ 4, 61, 51, 36],
       [21, 94, 51, 80],
       [50, 83, 78, 75],
       [ 7, 95, 41, 22],
       [85, 76, 20, 33]])

## Seed function:

In [25]:
np.random.seed(42)
x1=np.random.randint(1,11,5)
x1

array([7, 4, 8, 5, 7])

In [27]:
np.random.seed(108)
x2=np.random.randint(1,11,5)
x2

array([4, 8, 2, 7, 3])

In [28]:
np.random.seed(42)
x3=np.random.randint(1,11,5)
x3

array([7, 4, 8, 5, 7])

## Reshaping a numpy array:

In [29]:
ar1=np.arange(1,101,10)
ar1

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [30]:
ar1=ar1.reshape(5,2)
ar1

array([[ 1, 11],
       [21, 31],
       [41, 51],
       [61, 71],
       [81, 91]])

## Fetching the dimensions of a numpy array:

In [31]:
np1=np.random.randint(1,101,5)
np1.shape

(5,)

In [33]:
np2=np.random.randint(1,101,(4,5))
np2.shape

(4, 5)

## Finding the maximum and minimum elements in a numpy array and their indices:

In [34]:
y1=np.random.randint(1,101,(7,5))
y1

array([[59, 42, 92, 60, 80],
       [15, 62, 62, 47, 62],
       [51, 55, 64,  3, 51],
       [ 7, 21, 73, 39, 18],
       [ 4, 89, 60, 14,  9],
       [90, 53,  2, 84, 92],
       [60, 71, 44,  8, 47]])

### Finding the maximum value present in the numpy array:
### (The index values are given in terms of 1D array)

In [35]:
y1.max()

92

### Finding the minimum value present in the numpy array:

In [36]:
y1.min()

2

### Finding the index of maximum element in the array:

In [37]:
y1.argmax()

2

### Finding the index of minimum element in the array:

In [38]:
y1.argmin()

27