# Creating Numpy arrays

In [1]:
import numpy as np

## By transforming standard lists into NumPy array:

### For 1D arrays

In [2]:
l1=[1,2,3,4,5,6]
type(l1)

list

In [3]:
l1=np.array(l1)
l1

array([1, 2, 3, 4, 5, 6])

In [4]:
type(l1)

numpy.ndarray

### For 2D arrays

In [5]:
l2=[[1,2,3],[4,5,6]]
l2

[[1, 2, 3], [4, 5, 6]]

In [6]:
type(l2)

list

In [7]:
l2=np.array(l2)
l2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(l2)

numpy.ndarray

## By using Built-in Methods:

### arange() method

In [9]:
l3=np.arange(1,11)
l3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
l4=np.arange(0,21,3)
l4

array([ 0,  3,  6,  9, 12, 15, 18])

### zeros() method

In [12]:
l5=np.zeros(3)
l5

array([0., 0., 0.])

In [13]:
l6=np.zeros((4,4))
l6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### ones() method

In [15]:
l7=np.ones(4)
l7

array([1., 1., 1., 1.])

In [16]:
l8=np.ones((3,5))
l8

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace() method

In [17]:
l9=np.linspace(0,10,3)
l9

array([ 0.,  5., 10.])

In [21]:
l10=np.linspace(1,25,25)
l10

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

### eye() method (creating identity matrix)

In [23]:
l11=np.eye(5)
l11

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## By using Random module: