# NumPy Operations:

In [1]:
import numpy as np

In [2]:
x=np.random.randint(1,51,7)
x

array([41, 30,  6, 15, 21,  3, 33])

In [3]:
y=np.random.randint(1,51,(3,4))
y

array([[32, 47, 18, 31],
       [33, 43, 47, 15],
       [44, 39, 33, 31]])

## Normal arithmetic operations using integers:

In [4]:
x=x+5
x

array([46, 35, 11, 20, 26,  8, 38])

In [5]:
y=y+5

In [6]:
y

array([[37, 52, 23, 36],
       [38, 48, 52, 20],
       [49, 44, 38, 36]])

In [7]:
x=x-5
x

array([41, 30,  6, 15, 21,  3, 33])

In [8]:
y=y-5
y

array([[32, 47, 18, 31],
       [33, 43, 47, 15],
       [44, 39, 33, 31]])

In [9]:
x=x*3
x

array([123,  90,  18,  45,  63,   9,  99])

In [10]:
y=y*6
y

array([[192, 282, 108, 186],
       [198, 258, 282,  90],
       [264, 234, 198, 186]])

In [11]:
y=y/6
y

array([[32., 47., 18., 31.],
       [33., 43., 47., 15.],
       [44., 39., 33., 31.]])

In [12]:
y=y.astype(int)
y

array([[32, 47, 18, 31],
       [33, 43, 47, 15],
       [44, 39, 33, 31]])

In [13]:
x=x/3
x=x.astype(int)
x

array([41, 30,  6, 15, 21,  3, 33])

In [14]:
x=1/x
x

array([0.02439024, 0.03333333, 0.16666667, 0.06666667, 0.04761905,
       0.33333333, 0.03030303])

In [15]:
x=1/x
x

array([41., 30.,  6., 15., 21.,  3., 33.])

In [16]:
x=x.astype(int)
x

array([41, 30,  6, 15, 21,  3, 33])

In [17]:
y=1/y
y

array([[0.03125   , 0.0212766 , 0.05555556, 0.03225806],
       [0.03030303, 0.02325581, 0.0212766 , 0.06666667],
       [0.02272727, 0.02564103, 0.03030303, 0.03225806]])

In [18]:
y=1/y
y=y.astype(int)
y

array([[32, 47, 18, 31],
       [33, 43, 47, 15],
       [44, 39, 33, 31]])

In [19]:
a1=np.zeros(4)
a1

array([0., 0., 0., 0.])

In [20]:
a1=1/a1
a1

C:\Users\MYPC\AppData\Local\Temp\ipykernel_3848\3954794133.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a1=1/a1


array([inf, inf, inf, inf])

In [21]:
a1=1/a1
a1=a1.astype(int)
a1

array([0, 0, 0, 0])

In [22]:
a1=a1/a1
a1

C:\Users\MYPC\AppData\Local\Temp\ipykernel_3848\530315797.py:1: RuntimeWarning: invalid value encountered in true_divide
  a1=a1/a1


array([nan, nan, nan, nan])

### square roots:

In [24]:
c1=np.array([36,49,64,81,100,121,144,169,196,225,256,289,324,361])
c1=np.sqrt(c1)
c1

array([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.,
       19.])

### log values:

In [34]:
c2=np.array([2.72,100,1000,10000])
c2=np.log(c2)
c2

array([1.00063188, 4.60517019, 6.90775528, 9.21034037])

In [35]:
c2=c2.astype(int)

In [36]:
c2

array([1, 4, 6, 9])

### sine values:

In [46]:
c3=np.array([0,((22/7)/2),(22/7)/6])
c3=np.sin(c3)
c3

array([0.       , 0.9999998, 0.5001825])

In [47]:
x

array([41, 30,  6, 15, 21,  3, 33])

In [48]:
y

array([[32, 47, 18, 31],
       [33, 43, 47, 15],
       [44, 39, 33, 31]])

## returning sum,mean,variance,standard deviation,max and min elements in an array:

### for 1D array:

In [50]:
xa=x.sum()
xa

149

In [51]:
xb=x.mean()
xb

21.285714285714285

In [52]:
xc=x.var()
xc

172.77551020408163

In [53]:
xd=x.std()
xd

13.14440984616965

In [54]:
xmax=x.max()
xmax

41

### for 2D array:

#### for the sum of all the elements in the 2D array:

In [55]:
ya=y.sum()
ya

413

#### for the sum of all the elements in each column of the 2D array:

In [56]:
yac=y.sum(axis=0)
yac

array([109, 129,  98,  77])

#### for the sum of all the elements in each row of the 2D array:

In [57]:
yar=y.sum(axis=1)
yar

array([128, 138, 147])

#### for the mean of all the elements in each column of the 2D array:

In [60]:
yac=y.mean(axis=0)
yac

array([36.33333333, 43.        , 32.66666667, 25.66666667])

#### for the sum of all the elements in each row of the 2D array:

In [61]:
yar=y.mean(axis=1)
yar

array([32.  , 34.5 , 36.75])

#### for the variance of all the elements in each column of the 2D array:

In [62]:
yac=y.var(axis=0)
yac

array([ 29.55555556,  10.66666667, 140.22222222,  56.88888889])

#### for the variance of all the elements in each row of the 2D array:

In [64]:
yar=y.var(axis=1)
yar

array([105.5   , 152.75  ,  26.1875])