# NumPy Operations:

In [1]:
import numpy as np

In [2]:
x=np.random.randint(1,51,7)
x

array([18, 17, 17, 42, 36, 27,  7])

In [3]:
y=np.random.randint(1,51,(3,4))
y

array([[45,  3, 46, 25],
       [44, 36, 29, 26],
       [27, 46, 22, 14]])

## Normal arithmetic operations using integers:

In [4]:
x=x+5
x

array([23, 22, 22, 47, 41, 32, 12])

In [5]:
y=y+5

In [6]:
y

array([[50,  8, 51, 30],
       [49, 41, 34, 31],
       [32, 51, 27, 19]])

In [7]:
x=x-5
x

array([18, 17, 17, 42, 36, 27,  7])

In [8]:
y=y-5
y

array([[45,  3, 46, 25],
       [44, 36, 29, 26],
       [27, 46, 22, 14]])

In [9]:
x=x*3
x

array([ 54,  51,  51, 126, 108,  81,  21])

In [10]:
y=y*6
y

array([[270,  18, 276, 150],
       [264, 216, 174, 156],
       [162, 276, 132,  84]])

In [11]:
y=y/6
y

array([[45.,  3., 46., 25.],
       [44., 36., 29., 26.],
       [27., 46., 22., 14.]])

In [12]:
y=y.astype(int)
y

array([[45,  3, 46, 25],
       [44, 36, 29, 26],
       [27, 46, 22, 14]])

In [13]:
x=x/3
x=x.astype(int)
x

array([18, 17, 17, 42, 36, 27,  7])

In [14]:
x=1/x
x

array([0.05555556, 0.05882353, 0.05882353, 0.02380952, 0.02777778,
       0.03703704, 0.14285714])

In [15]:
x=1/x
x

array([18., 17., 17., 42., 36., 27.,  7.])

In [16]:
x=x.astype(int)
x

array([18, 17, 17, 42, 36, 27,  7])

In [17]:
y=1/y
y

array([[0.02222222, 0.33333333, 0.02173913, 0.04      ],
       [0.02272727, 0.02777778, 0.03448276, 0.03846154],
       [0.03703704, 0.02173913, 0.04545455, 0.07142857]])

In [18]:
y=1/y
y=y.astype(int)
y

array([[45,  3, 46, 25],
       [44, 36, 29, 26],
       [27, 46, 22, 14]])

In [19]:
a1=np.zeros(4)
a1

array([0., 0., 0., 0.])

In [20]:
a1=1/a1
a1

C:\Users\MYPC\AppData\Local\Temp\ipykernel_24560\3954794133.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a1=1/a1


array([inf, inf, inf, inf])

In [21]:
a1=1/a1
a1=a1.astype(int)
a1

array([0, 0, 0, 0])

In [22]:
a1=a1/a1
a1

C:\Users\MYPC\AppData\Local\Temp\ipykernel_24560\530315797.py:1: RuntimeWarning: invalid value encountered in true_divide
  a1=a1/a1


array([nan, nan, nan, nan])

### square roots:

In [23]:
c1=np.array([36,49,64,81,100,121,144,169,196,225,256,289,324,361])
c1=np.sqrt(c1)
c1

array([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.,
       19.])

### log values:

In [24]:
c2=np.array([2.72,100,1000,10000])
c2=np.log(c2)
c2

array([1.00063188, 4.60517019, 6.90775528, 9.21034037])

In [25]:
c2=c2.astype(int)

In [26]:
c2

array([1, 4, 6, 9])

### sine values:

In [27]:
c3=np.array([0,((22/7)/2),(22/7)/6])
c3=np.sin(c3)
c3

array([0.       , 0.9999998, 0.5001825])

In [28]:
x

array([18, 17, 17, 42, 36, 27,  7])

In [29]:
y

array([[45,  3, 46, 25],
       [44, 36, 29, 26],
       [27, 46, 22, 14]])

## returning sum,mean,variance,standard deviation,max and min elements in an array:

### for 1D array:

In [30]:
xa=x.sum()
xa

164

In [31]:
xb=x.mean()
xb

23.428571428571427

In [32]:
xc=x.var()
xc

128.24489795918367

In [33]:
xd=x.std()
xd

11.324526390060807

In [34]:
xmax=x.max()
xmax

42

### for 2D array:

#### for the sum of all the elements in the 2D array:

In [35]:
ya=y.sum()
ya

363

#### for the sum of all the elements in each column of the 2D array:

In [36]:
yac=y.sum(axis=0)
yac

array([116,  85,  97,  65])

#### for the sum of all the elements in each row of the 2D array:

In [37]:
yar=y.sum(axis=1)
yar

array([119, 135, 109])

#### for the mean of all the elements in each column of the 2D array:

In [38]:
yac=y.mean(axis=0)
yac

array([38.66666667, 28.33333333, 32.33333333, 21.66666667])

#### for the sum of all the elements in each row of the 2D array:

In [39]:
yar=y.mean(axis=1)
yar

array([29.75, 33.75, 27.25])

#### for the variance of all the elements in each column of the 2D array:

In [40]:
yac=y.var(axis=0)
yac

array([ 68.22222222, 337.55555556, 101.55555556,  29.55555556])

#### for the variance of all the elements in each row of the 2D array:

In [41]:
yar=y.var(axis=1)
yar

array([308.6875,  48.1875, 138.6875])

In [44]:
a=np.array([[30,60,90],[20,40,60],[80,120,40]])
b=np.array([[3,6,9],[2,4,6],[8,12,4]])
c=a/b
c

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [45]:
d=a+b
d

array([[ 33,  66,  99],
       [ 22,  44,  66],
       [ 88, 132,  44]])

In [46]:
d=d*11
d

array([[ 363,  726, 1089],
       [ 242,  484,  726],
       [ 968, 1452,  484]])

In [48]:
d=d/121
d

array([[ 3.,  6.,  9.],
       [ 2.,  4.,  6.],
       [ 8., 12.,  4.]])

In [49]:
d=d*c
d

array([[ 30.,  60.,  90.],
       [ 20.,  40.,  60.],
       [ 80., 120.,  40.]])